image: myubuntu:1.0.0

stages:
  - build
  - test
build app:
    stage: build
    script:
      - echo "hello world" 
    tags:
      - ubuntu-ng
unit-test:
    stage: test
    script:
      - echo "hello test" 
    tags:
      - ubuntu-ng